# We want to use the KVM-based system, so require sudo
sudo: required
services:
  - docker

before_install:
  - plugin_name=${PWD##*/} && echo $plugin_name
  - chmod -R 777 .

script:
  - >
    docker run
    -e "COMMIT_HASH=origin/tests-passed"
    -e "SKIP_LINT=1"
    -e "RUBY_ONLY=1"
    -e SINGLE_PLUGIN=$plugin_name
    -v $(pwd):/var/www/discourse/plugins/$plugin_name
    discourse/discourse_test:release

after_success:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client
  - sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
  - tx push -s
