plugins:
  events_enabled:
    default: false
    client: true
  events_add_to_calendar:
    client: true
    default: false
  events_event_label_icon:
    client: true
    default: 'calendar'
  events_event_label_no_text:
    client: true
    default: false
  events_event_label_format:
    client: true
    default: 'MMMM Do, HH:mm'
  events_event_label_short_format:
    client: true
    default: 'M-D, HH:mm'
  events_event_label_short_only_start:
    client: true
    default: false
  events_remove_past_from_agenda:
    default: false
  events_remove_past_from_map:
    default: false
  events_agenda_filter_closed:
    default: false
  events_event_label_include_timezone:
    client: true
    default: false
  events_default_timezone:
    default: 'Etc/UTC'
    client: true
    enum: 'EventsDefaultTimezoneSiteSetting'
  events_hamburger_menu_calendar_link:
    default: false
    client: true
  events_hamburger_menu_agenda_link:
    default: false
    client: true
  events_min_trust_to_create:
    default: 0
